services:
  vpn-client:
    build: .
    command: ["sh", "-c", "sleep infinity"]
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - .:/app
    networks:
      vpn-net:
        ipv4_address: 172.28.0.2

  vpn-server:
    build: .
    command: ["sh", "-c", "sleep infinity"]
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - .:/app
    networks:
      vpn-net:
        ipv4_address: 172.28.0.3

networks:
  vpn-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
